baseURL = "https://example.org/"
defaultContentLanguage = "en"
enableRobotsTXT = true
theme = "gokarna"
title = "Cristina Leon"

[menus]
  [[menus.main]]
    identifier = 'home'
    name = 'Home'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    identifier = 'Posts'
    name = 'Posts'
    pageRef = '/posts'
    weight = 2
  [[menus.main]]
    identifier = 'about'
    name = 'About'
    pageRef = '/about'
    weight = 3
  [[menus.main]]
    identifier = "contact"
    name = "Contact"
    weight = 4

# Multilingual configuration
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    languageCode = "en-us"
    contentDir = "content/en"

    # English params
    [languages.en.params]
      description = "Computer Science major with a Physics minor at University of Marburg"
      metaKeywords = ["blog", "computer science", "university"]

  [languages.de]
    languageName = "Deutsch"
    weight = 2
    languageCode = "de-de"
    contentDir = "content/de"

    # German params
    [languages.de.params]
      description = "Informatik-Studentin mit Physik-Nebenfach an der Phillips-Universität Marburg"
      metaKeywords = ["blog", "informatik", "universität"]

# Global params
[params]
  accentColor = "#FF4D4D"
  avatarURL = "/images/avatar.webp"
  avatarAltText = "avatar"
  avatarSize = "size-m"
  dateFormat = "January 2, 2006"
  numberPostsOnHomePage = 4
  showBackToTopButton = true
  showPostsOnHomePage = ""
  togglePreviousAndNextButtons = false
  socialIcons = [
    {name = "github", url = "https://github.com/ctrleon"},
    {name = "email", url = "mailto:cristinaleon@posteo.com"},
    {name = "gnuprivacyguard", url = ""},
    {name = "rss", url = "https://example.com"},
  ]
  customHeadHTML = '''
    <!-- Your existing Katex config -->
  '''

[minify]
  minifyOutput = true