baseURL = "https://example.org/"
defaultContentLanguage = "en"
enableRobotsTXT = true
theme = "gokarna"
title = "Cristina Leon"

# Multilingual configuration
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    languageCode = "en-us"
    contentDir = "content/en"

    # English menu
    [[languages.en.menu.main]]
      name = "Posts"
      url = "/posts/"
      weight = 1

    [[languages.en.menu.main]]
      name = "Tags"
      url = "/tags/"
      weight = 2

    [[languages.en.menu.main]]
      name = "About"
      url = "/about/"
      weight = 3

    [[languages.en.menu.main]]
      identifier = "github"
      url = "https://github.com/ctrleon"
      weight = 4
      pre = "<span data-feather='github'></span>"
      [languages.en.menu.main.params]
        newPage = true

    # English params
    [languages.en.params]
      description = "Computer Science major with a Physics minor at University of Marburg"
      footer = "Cristina Leon"
      metaKeywords = ["blog", "programming", "germany"]

  [languages.de]
    languageName = "Deutsch"
    weight = 2
    languageCode = "de-de"
    contentDir = "content/de"

    # German menu 
    [[languages.de.menu.main]]
      name = "Beiträge"
      url = "/de/posts/"
      weight = 1

    [[languages.de.menu.main]]
      name = "Schlagwörter"
      url = "/de/tags/"
      weight = 2

    [[languages.de.menu.main]]
      name = "Über mich"
      url = "/de/about/"
      weight = 3

    [[languages.de.menu.main]]
      identifier = "github"
      url = "https://github.com/ctrleon"
      weight = 4
      pre = "<span data-feather='github'></span>"
      [languages.de.menu.main.params]
        newPage = true

    # German params
    [languages.de.params]
      description = "Informatik-Studentin mit Physik-Nebenfach an der Phillips-Universität Marburg"
      footer = "Cristina Leon"
      metaKeywords = ["blog", "programmierung", "deutschland"]

# Global params
[params]
  accentColor = "#FF4D4D"
  avatarURL = "/images/avatar.webp"
  avatarAltText = "X X's avatar"
  avatarSize = "size-m"
  dateFormat = "January 2, 2006"
  numberPostsOnHomePage = 4
  showBackToTopButton = true
  showPostsOnHomePage = ""
  togglePreviousAndNextButtons = false
  socialIcons = [
    {name = "github", url = "https://github.com/ctrleon"},
    {name = "email", url = "mailto:cristinaleon@posteo.com"},
    {name = "rss", url = "https://example.com"},
  ]
  customHeadHTML = '''
    <!-- Your existing Katex config -->
  '''

[minify]
  minifyOutput = true